name: Test, build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  bamba:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
    # The above line will set up NodeJS (the latest version ) because we are deploying a VueJS project.         
    - run: npm install
    # At this point, Github Action has spun out a Ubuntu Virtual Machine, installed all its dependencies plus Node in above line and the above line installs all the dependencies of your projects        
    - run: npm run build

    - name: Copy repository contents to remote server via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.BAMBA_HOST }}
        username: ${{ secrets.BAMBA_USERNAME }}
        port: ${{ secrets.BAMBA_PORT }}
        key: ${{ secrets.BAMBA_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "."
        target: ${{ secrets.BAMBA_DIR }}
    - name: SSH to Server
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.BAMBA_HOST }}
        username: ${{ secrets.BAMBA_USERNAME }}
        #password: ${{ secrets.SSH_USER_PASSWORD }}
        key: ${{ secrets.BAMBA_KEY }}
        port: ${{ secrets.BAMBA_PORT }}
        debug: true
        script: |
            whoami
            sudo apt update
            sudo apt upgrade
            npm install
            ls -al
            cd ${{secrets.BAMBA_DIR}} && npm install
            npm run build
